package com.example.travel.models

data class ResultResponse(
    val access: String?,
    val accommodates: Int?,
    val amenities: List<String>?,
    val bathrooms: Int?,
    val bed_type: String?,
    val bedrooms: Int?,
    val beds: Int?,
    val booked_dates: List<String>?,
    val calculated_host_listings_count: Int?,
    val calendar_updated: String?,
    val cancellation_policy: String?,
    val city: String?,
    val cleaning_fee: Int?,
    val country: String?,
    val country_code: String?,
    val description: String?,
    val experiences_offered: String?,
    val extra_people: Int?,
    val first_review: String?,
    val geolocation: Geolocation?,
    val guests_included: Int?,
    val host_about: String?,
    val host_acceptance_rate: Any?,
    val host_id: String?,
    val host_listings_count: Int?,
    val host_location: String?,
    val host_name: String?,
    val host_neighbourhood: String?,
    val host_picture_url: String?,
    val host_response_rate: Int?,
    val host_response_time: String?,
    val host_since: String?,
    val host_thumbnail_url: String?,
    val host_total_listings_count: Int?,
    val host_verifications: List<String>?,
    val house_rules: String?,
    val id: String,
    val interaction: String?,
    val last_review: String?,
    val latitude: String?,
    val longitude: String?,
    val market: String?,
    val maximum_nights: Int?,
    val minimum_nights: Int?,
    val monthly_price: Int?,
    val name: String?,
    val neighborhood_overview: String?,
    val neighbourhood: String?,
    val neighbourhood_cleansed: String?,
    val neighbourhood_group_cleansed: String?,
    val notes: String?,
    val number_of_reviews: Int?,
    val photos: List<String>?,
    val price: Int?,
    val property_type: String?,
    val review_scores_accuracy: Int?,
    val review_scores_checkin: Int?,
    val review_scores_cleanliness: Int?,
    val review_scores_communication: Int?,
    val review_scores_location: Int?,
    val review_scores_rating: Int?,
    val review_scores_value: Int?,
    val reviews_per_month: Double?,
    val room_type: String?,
    val security_deposit: Int?,
    val smart_location: String?,
    val space: String?,
    val state: String?,
    val street: String?,
    val summary: String?,
    val transit: String?,
    val weekly_price: Int?,
    val zipcode: String?
)


internal fun ResultResponse.toResult(): Result {
    return Result(
        access,
        accommodates,
        amenities,
        bathrooms,
        bed_type,
        bedrooms,
        beds,
        booked_dates,
        calculated_host_listings_count,
        calendar_updated,
        cancellation_policy,
        city,
        cleaning_fee,
        country,
        country_code,
        description,
        experiences_offered,
        extra_people,
        first_review,
        geolocation,
        guests_included,
        host_about,
        host_acceptance_rate,
        host_id,
        host_listings_count,
        host_location,
        host_name,
        host_neighbourhood,
        host_picture_url,
        host_response_rate,
        host_response_time,
        host_since,
        host_thumbnail_url,
        host_total_listings_count,
        host_verifications,
        house_rules,
        id,
        interaction,
        last_review,
        latitude,
        longitude,
        market,
        maximum_nights,
        minimum_nights,
        monthly_price,
        name,
        neighborhood_overview,
        neighbourhood,
        neighbourhood_cleansed,
        neighbourhood_group_cleansed,
        notes,
        number_of_reviews,
        photos,
        price,
        property_type,
        review_scores_accuracy,
        review_scores_checkin,
        review_scores_cleanliness,
        review_scores_communication,
        review_scores_location,
        review_scores_rating,
        review_scores_value,
        reviews_per_month,
        room_type,
        security_deposit,
        smart_location,
        space,
        state,
        street,
        summary,
        transit,
        weekly_price,
        zipcode
    )
}